### ISSUE TITLE
The value tooltip shows strange values

### ISSUE THREAD

**Issue by lsteynen** [jgeudens/GraphViewer#40] opened 2017-07-07 18:22 UTC
With the attached file, the "Show value tooltip" shows the correct values. But when "Time data in milliseconds" is turned off, the tooltip shows strange values.
[Modbusscope.zip](https://github.com/jgeudens/GraphViewer/files/1131929/Modbusscope.zip)

**Comment by jgeudens** [comment] 2017-07-13 06:33
Duplicate of fixed issue #36

**Closed as completed by jgeudens** 2017-07-13 06:33 UTC
Labels: duplicate
